name: Update vuln-list repo
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update repo vuln-list
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      VULN_LIST_DIR: "vuln-list"
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Check out vuln-list repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.repository_owner }}/vuln-list
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: ${{ env.VULN_LIST_DIR }}

      - name: Setup github user email and name
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Compile vuln-list-update
        run: go build -o vuln-list-update .

      - name: Alpine Unfixed Vulnerability Tracker
        run: ./scripts/update.sh alpine-unfixed "Alpine Secshfixes Tracker"
